# The top-level 'version' key has been removed as it is obsolete.

services:
  # Frontend React application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8080

  # Backend Spring Boot application  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # This line forces Docker to use the amd64 version, resolving the 
    # 'no match for platform' error on arm64 machines (e.g., Apple M1/M2/M3).
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tradingplatform?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SERVER_PORT=8080

  # MySQL Database
  mysql:
    image: mysql:8.0
    # This is a proactive addition to prevent similar platform issues with the MySQL image.
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tradingplatform
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: